/** Don't edit manually only color names. Generated by script: ./tools/icons/generate-colors.ts */
export const iconColors = {
  darkblue: {day: '#196dffff', night: '#3d7effff'},
  white: {day: '#ffffffff', night: '#4c4c4cff'},
  lavender: {day: '#9c89f9ff', night: '#7869d5ff'},
  brightgreen: {day: '#6ec901ff', night: '#498801ff'},
  tulip: {day: '#f99090ff', night: '#bb5a5cff'},
  pink: {day: '#f48bb5ff', night: '#ba5681ff'},
  brightlilac: {day: '#d38de0ff', night: '#a15fafff'},
  red: {day: '#e63d2eff', night: '#e43b2dff'},
  silver: {day: '#abaeb2ff', night: '#76797cff'},
  brightblue: {day: '#3377e4ff', night: '#0278f2ff'},
  lightblue: {day: '#60a8f0ff', night: '#237dc1ff'},
  blue: {day: '#5eb3edff', night: '#0181b8ff'},
  lightgreen: {day: '#69bfa9ff', night: '#2d8673ff'},
  green: {day: '#8cc157ff', night: '#018a45ff'},
  orange: {day: '#ffa15eff', night: '#c15a37ff'},
  crayola: {day: '#a9a9bbff', night: '#7c81b4ff'}
} as const;
export type IconColor = keyof typeof iconColors;
