/** Don't edit manually. Generated by script: ./tools/icons/generate-imports.ts */
import administration_24 from '../../static/icons/administration_24.svg';
import airfield_24 from '../../static/icons/airfield_24.svg';
import airport_24 from '../../static/icons/airport_24.svg';
import animation_24 from '../../static/icons/animation_24.svg';
import aquarium_24 from '../../static/icons/aquarium_24.svg';
import architect_bureau_24 from '../../static/icons/architect_bureau_24.svg';
import armenian_church_24 from '../../static/icons/armenian_church_24.svg';
import art_24 from '../../static/icons/art_24.svg';
import atm_24 from '../../static/icons/atm_24.svg';
import attraction_24 from '../../static/icons/attraction_24.svg';
import auto_24 from '../../static/icons/auto_24.svg';
import auto_parts_24 from '../../static/icons/auto_parts_24.svg';
import auto_repair_24 from '../../static/icons/auto_repair_24.svg';
import baby_shop_24 from '../../static/icons/baby_shop_24.svg';
import banks_24 from '../../static/icons/banks_24.svg';
import bars_24 from '../../static/icons/bars_24.svg';
import baths_24 from '../../static/icons/baths_24.svg';
import beach_24 from '../../static/icons/beach_24.svg';
import beauty_24 from '../../static/icons/beauty_24.svg';
import beauty_shops_24 from '../../static/icons/beauty_shops_24.svg';
import beer_market_24 from '../../static/icons/beer_market_24.svg';
import bike_24 from '../../static/icons/bike_24.svg';
import bike_rent_24 from '../../static/icons/bike_rent_24.svg';
import boat_station_24 from '../../static/icons/boat_station_24.svg';
import bookstore_24 from '../../static/icons/bookstore_24.svg';
import bowling_24 from '../../static/icons/bowling_24.svg';
import buddhism_24 from '../../static/icons/buddhism_24.svg';
import building_24 from '../../static/icons/building_24.svg';
import bus_24 from '../../static/icons/bus_24.svg';
import bus_station_24 from '../../static/icons/bus_station_24.svg';
import bus_stop_24 from '../../static/icons/bus_stop_24.svg';
import butcher_shop_24 from '../../static/icons/butcher_shop_24.svg';
import cableway_24 from '../../static/icons/cableway_24.svg';
import cafe_24 from '../../static/icons/cafe_24.svg';
import canteen_24 from '../../static/icons/canteen_24.svg';
import car_24 from '../../static/icons/car_24.svg';
import car_park_24 from '../../static/icons/car_park_24.svg';
import car_park_barrier_24 from '../../static/icons/car_park_barrier_24.svg';
import car_park_covered_24 from '../../static/icons/car_park_covered_24.svg';
import car_park_disabled_24 from '../../static/icons/car_park_disabled_24.svg';
import car_park_taxi_24 from '../../static/icons/car_park_taxi_24.svg';
import car_park_toll_24 from '../../static/icons/car_park_toll_24.svg';
import car_wash_24 from '../../static/icons/car_wash_24.svg';
import cart_parking_24 from '../../static/icons/cart_parking_24.svg';
import catholic_church_24 from '../../static/icons/catholic_church_24.svg';
import cemetery_24 from '../../static/icons/cemetery_24.svg';
import checkpoint_24 from '../../static/icons/checkpoint_24.svg';
import childrens_camp_24 from '../../static/icons/childrens_camp_24.svg';
import childrens_playground_24 from '../../static/icons/childrens_playground_24.svg';
import cinemas_24 from '../../static/icons/cinemas_24.svg';
import circus_24 from '../../static/icons/circus_24.svg';
import clothes_shop_24 from '../../static/icons/clothes_shop_24.svg';
import college_24 from '../../static/icons/college_24.svg';
import concert_hall_24 from '../../static/icons/concert_hall_24.svg';
import confectionary_24 from '../../static/icons/confectionary_24.svg';
import construction_hypermarket_24 from '../../static/icons/construction_hypermarket_24.svg';
import construction_tool_24 from '../../static/icons/construction_tool_24.svg';
import country_24 from '../../static/icons/country_24.svg';
import currency_exchange_24 from '../../static/icons/currency_exchange_24.svg';
import currency_exchange_fallback_24 from '../../static/icons/currency_exchange_fallback_24.svg';
import dairy_24 from '../../static/icons/dairy_24.svg';
import dancehall_24 from '../../static/icons/dancehall_24.svg';
import dental_24 from '../../static/icons/dental_24.svg';
import district_24 from '../../static/icons/district_24.svg';
import dolmus_24 from '../../static/icons/dolmus_24.svg';
import driving_school_24 from '../../static/icons/driving_school_24.svg';
import drop_off_24 from '../../static/icons/drop_off_24.svg';
import drugstores_24 from '../../static/icons/drugstores_24.svg';
import dry_cleaning_24 from '../../static/icons/dry_cleaning_24.svg';
import electronics_24 from '../../static/icons/electronics_24.svg';
import emergency_24 from '../../static/icons/emergency_24.svg';
import entertainments_24 from '../../static/icons/entertainments_24.svg';
import entrance_24 from '../../static/icons/entrance_24.svg';
import equestrian_24 from '../../static/icons/equestrian_24.svg';
import exhibition_center_24 from '../../static/icons/exhibition_center_24.svg';
import factory_24 from '../../static/icons/factory_24.svg';
import fallback_24 from '../../static/icons/fallback_24.svg';
import fast_food_24 from '../../static/icons/fast_food_24.svg';
import fast_tram_24 from '../../static/icons/fast_tram_24.svg';
import festival_24 from '../../static/icons/festival_24.svg';
import film_studio_24 from '../../static/icons/film_studio_24.svg';
import fire_station_24 from '../../static/icons/fire_station_24.svg';
import fish_store_24 from '../../static/icons/fish_store_24.svg';
import fitness_24 from '../../static/icons/fitness_24.svg';
import flower_shop_24 from '../../static/icons/flower_shop_24.svg';
import food_market_24 from '../../static/icons/food_market_24.svg';
import forest_24 from '../../static/icons/forest_24.svg';
import fountain_24 from '../../static/icons/fountain_24.svg';
import funicular_24 from '../../static/icons/funicular_24.svg';
import furniture_store_24 from '../../static/icons/furniture_store_24.svg';
import gallery_24 from '../../static/icons/gallery_24.svg';
import garage_cooperative_24 from '../../static/icons/garage_cooperative_24.svg';
import garden_24 from '../../static/icons/garden_24.svg';
import gasstation_24 from '../../static/icons/gasstation_24.svg';
import gastro_market_24 from '../../static/icons/gastro_market_24.svg';
import geyser_24 from '../../static/icons/geyser_24.svg';
import giftshop_24 from '../../static/icons/giftshop_24.svg';
import golf_24 from '../../static/icons/golf_24.svg';
import government_24 from '../../static/icons/government_24.svg';
import grass_24 from '../../static/icons/grass_24.svg';
import greengrocery_24 from '../../static/icons/greengrocery_24.svg';
import hairdressers_24 from '../../static/icons/hairdressers_24.svg';
import haulier_24 from '../../static/icons/haulier_24.svg';
import helicopter_24 from '../../static/icons/helicopter_24.svg';
import home_appliances_24 from '../../static/icons/home_appliances_24.svg';
import hospital_24 from '../../static/icons/hospital_24.svg';
import hostels_24 from '../../static/icons/hostels_24.svg';
import hotels_24 from '../../static/icons/hotels_24.svg';
import household_supplies_24 from '../../static/icons/household_supplies_24.svg';
import hydro_24 from '../../static/icons/hydro_24.svg';
import hypermarket_24 from '../../static/icons/hypermarket_24.svg';
import indoor_exit_24 from '../../static/icons/indoor_exit_24.svg';
import indoor_info_arrival_24 from '../../static/icons/indoor_info_arrival_24.svg';
import indoor_info_departure_24 from '../../static/icons/indoor_info_departure_24.svg';
import indoor_info_inquiry_office_24 from '../../static/icons/indoor_info_inquiry_office_24.svg';
import indoor_info_meetingpoint_24 from '../../static/icons/indoor_info_meetingpoint_24.svg';
import indoor_info_schedule_24 from '../../static/icons/indoor_info_schedule_24.svg';
import indoor_info_scheme_24 from '../../static/icons/indoor_info_scheme_24.svg';
import indoor_info_stand_24 from '../../static/icons/indoor_info_stand_24.svg';
import indoor_infra_control_frame_24 from '../../static/icons/indoor_infra_control_frame_24.svg';
import indoor_infra_elevator_24 from '../../static/icons/indoor_infra_elevator_24.svg';
import indoor_infra_elevator_disabled_24 from '../../static/icons/indoor_infra_elevator_disabled_24.svg';
import indoor_infra_emergency_exit_24 from '../../static/icons/indoor_infra_emergency_exit_24.svg';
import indoor_infra_escalator_24 from '../../static/icons/indoor_infra_escalator_24.svg';
import indoor_infra_fire_stairs_24 from '../../static/icons/indoor_infra_fire_stairs_24.svg';
import indoor_infra_luggage_inspection_24 from '../../static/icons/indoor_infra_luggage_inspection_24.svg';
import indoor_infra_pandus_24 from '../../static/icons/indoor_infra_pandus_24.svg';
import indoor_infra_stairs_24 from '../../static/icons/indoor_infra_stairs_24.svg';
import indoor_infra_travolator_24 from '../../static/icons/indoor_infra_travolator_24.svg';
import indoor_leisure_scene_24 from '../../static/icons/indoor_leisure_scene_24.svg';
import indoor_serivce_smoking_room_24 from '../../static/icons/indoor_serivce_smoking_room_24.svg';
import indoor_service_charging_socket_24 from '../../static/icons/indoor_service_charging_socket_24.svg';
import indoor_service_checkin_desk_24 from '../../static/icons/indoor_service_checkin_desk_24.svg';
import indoor_service_fitting_room_24 from '../../static/icons/indoor_service_fitting_room_24.svg';
import indoor_service_luggage_24 from '../../static/icons/indoor_service_luggage_24.svg';
import indoor_service_luggage_claim_24 from '../../static/icons/indoor_service_luggage_claim_24.svg';
import indoor_service_luggage_oversized_claim_24 from '../../static/icons/indoor_service_luggage_oversized_claim_24.svg';
import indoor_service_luggage_oversized_dropoff_24 from '../../static/icons/indoor_service_luggage_oversized_dropoff_24.svg';
import indoor_service_luggage_storage_24 from '../../static/icons/indoor_service_luggage_storage_24.svg';
import indoor_service_shopping_cart_parking_24 from '../../static/icons/indoor_service_shopping_cart_parking_24.svg';
import indoor_service_shower_24 from '../../static/icons/indoor_service_shower_24.svg';
import indoor_service_ticket_office_24 from '../../static/icons/indoor_service_ticket_office_24.svg';
import indoor_service_waiting_room_24 from '../../static/icons/indoor_service_waiting_room_24.svg';
import indoor_service_wardrobe_24 from '../../static/icons/indoor_service_wardrobe_24.svg';
import indoor_service_wheelchair_rent_24 from '../../static/icons/indoor_service_wheelchair_rent_24.svg';
import industrial_enterprise_24 from '../../static/icons/industrial_enterprise_24.svg';
import information_24 from '../../static/icons/information_24.svg';
import it_24 from '../../static/icons/it_24.svg';
import jewelry_store_24 from '../../static/icons/jewelry_store_24.svg';
import justice_24 from '../../static/icons/justice_24.svg';
import kindergarten_24 from '../../static/icons/kindergarten_24.svg';
import landmark_24 from '../../static/icons/landmark_24.svg';
import laundry_24 from '../../static/icons/laundry_24.svg';
import library_24 from '../../static/icons/library_24.svg';
import liquor_store_24 from '../../static/icons/liquor_store_24.svg';
import locality_24 from '../../static/icons/locality_24.svg';
import locker_24 from '../../static/icons/locker_24.svg';
import malls_24 from '../../static/icons/malls_24.svg';
import market_24 from '../../static/icons/market_24.svg';
import marketplace_24 from '../../static/icons/marketplace_24.svg';
import medical_24 from '../../static/icons/medical_24.svg';
import medicine_24 from '../../static/icons/medicine_24.svg';
import memorable_event_24 from '../../static/icons/memorable_event_24.svg';
import metro_24 from '../../static/icons/metro_24.svg';
import metro_bus_24 from '../../static/icons/metro_bus_24.svg';
import metro_cable_24 from '../../static/icons/metro_cable_24.svg';
import metro_funicular_24 from '../../static/icons/metro_funicular_24.svg';
import metro_light_24 from '../../static/icons/metro_light_24.svg';
import metro_monorail_24 from '../../static/icons/metro_monorail_24.svg';
import metro_tram_24 from '../../static/icons/metro_tram_24.svg';
import mobile_phones_24 from '../../static/icons/mobile_phones_24.svg';
import monument_24 from '../../static/icons/monument_24.svg';
import mosque_24 from '../../static/icons/mosque_24.svg';
import mountain_24 from '../../static/icons/mountain_24.svg';
import museum_24 from '../../static/icons/museum_24.svg';
import music_store_24 from '../../static/icons/music_store_24.svg';
import musicclub_24 from '../../static/icons/musicclub_24.svg';
import nail_studio_24 from '../../static/icons/nail_studio_24.svg';
import news_24 from '../../static/icons/news_24.svg';
import night_club_24 from '../../static/icons/night_club_24.svg';
import office_24 from '../../static/icons/office_24.svg';
import office_service_24 from '../../static/icons/office_service_24.svg';
import online_store_24 from '../../static/icons/online_store_24.svg';
import opticial_store_24 from '../../static/icons/opticial_store_24.svg';
import orthodox_church_24 from '../../static/icons/orthodox_church_24.svg';
import park_24 from '../../static/icons/park_24.svg';
import pawnshop_24 from '../../static/icons/pawnshop_24.svg';
import pedestrian_24 from '../../static/icons/pedestrian_24.svg';
import perfume_shop_24 from '../../static/icons/perfume_shop_24.svg';
import pet_playground_24 from '../../static/icons/pet_playground_24.svg';
import petshop_24 from '../../static/icons/petshop_24.svg';
import photo_24 from '../../static/icons/photo_24.svg';
import picnic_24 from '../../static/icons/picnic_24.svg';
import pier_24 from '../../static/icons/pier_24.svg';
import pizzeria_24 from '../../static/icons/pizzeria_24.svg';
import planetarium_24 from '../../static/icons/planetarium_24.svg';
import playground_24 from '../../static/icons/playground_24.svg';
import police_24 from '../../static/icons/police_24.svg';
import police_post_24 from '../../static/icons/police_post_24.svg';
import pool_hall_24 from '../../static/icons/pool_hall_24.svg';
import port_24 from '../../static/icons/port_24.svg';
import post_festival_24 from '../../static/icons/post_festival_24.svg';
import post_office_24 from '../../static/icons/post_office_24.svg';
import printing_services_24 from '../../static/icons/printing_services_24.svg';
import protestant_church_24 from '../../static/icons/protestant_church_24.svg';
import province_24 from '../../static/icons/province_24.svg';
import pub_24 from '../../static/icons/pub_24.svg';
import racing_24 from '../../static/icons/racing_24.svg';
import railway_entrance_24 from '../../static/icons/railway_entrance_24.svg';
import railway_station_24 from '../../static/icons/railway_station_24.svg';
import railway_terminal_24 from '../../static/icons/railway_terminal_24.svg';
import restaurants_24 from '../../static/icons/restaurants_24.svg';
import rezervation_24 from '../../static/icons/rezervation_24.svg';
import route_24 from '../../static/icons/route_24.svg';
import sanatorium_24 from '../../static/icons/sanatorium_24.svg';
import school_24 from '../../static/icons/school_24.svg';
import science_24 from '../../static/icons/science_24.svg';
import shoe_store_24 from '../../static/icons/shoe_store_24.svg';
import shooting_24 from '../../static/icons/shooting_24.svg';
import skating_rink_24 from '../../static/icons/skating_rink_24.svg';
import ski_resort_24 from '../../static/icons/ski_resort_24.svg';
import software_24 from '../../static/icons/software_24.svg';
import spa_24 from '../../static/icons/spa_24.svg';
import sport_24 from '../../static/icons/sport_24.svg';
import sport_school_24 from '../../static/icons/sport_school_24.svg';
import sportcenter_24 from '../../static/icons/sportcenter_24.svg';
import sports_bar_24 from '../../static/icons/sports_bar_24.svg';
import spring_24 from '../../static/icons/spring_24.svg';
import stadium_24 from '../../static/icons/stadium_24.svg';
import stage_24 from '../../static/icons/stage_24.svg';
import standpipe_24 from '../../static/icons/standpipe_24.svg';
import stationery_store_24 from '../../static/icons/stationery_store_24.svg';
import stenograffia_24 from '../../static/icons/stenograffia_24.svg';
import street_24 from '../../static/icons/street_24.svg';
import supermarket_24 from '../../static/icons/supermarket_24.svg';
import sushi_24 from '../../static/icons/sushi_24.svg';
import swimming_pool_24 from '../../static/icons/swimming_pool_24.svg';
import synagogue_24 from '../../static/icons/synagogue_24.svg';
import tableware_24 from '../../static/icons/tableware_24.svg';
import tailor_24 from '../../static/icons/tailor_24.svg';
import taxfree_24 from '../../static/icons/taxfree_24.svg';
import taxi_24 from '../../static/icons/taxi_24.svg';
import tennis_24 from '../../static/icons/tennis_24.svg';
import theatre_24 from '../../static/icons/theatre_24.svg';
import ticket_office_24 from '../../static/icons/ticket_office_24.svg';
import tire_fitting_24 from '../../static/icons/tire_fitting_24.svg';
import tram_24 from '../../static/icons/tram_24.svg';
import tram_stop_24 from '../../static/icons/tram_stop_24.svg';
import transport_bus_24 from '../../static/icons/transport_bus_24.svg';
import transport_tram_24 from '../../static/icons/transport_tram_24.svg';
import trash_24 from '../../static/icons/trash_24.svg';
import travel_agency_24 from '../../static/icons/travel_agency_24.svg';
import university_24 from '../../static/icons/university_24.svg';
import urban_gov_station_administration_24 from '../../static/icons/urban_gov_station_administration_24.svg';
import urban_gov_station_attendant_24 from '../../static/icons/urban_gov_station_attendant_24.svg';
import urban_leisure_house_of_culture_24 from '../../static/icons/urban_leisure_house_of_culture_24.svg';
import urban_med_first_aid_post_24 from '../../static/icons/urban_med_first_aid_post_24.svg';
import urban_roadnet_parking_free_bld_24 from '../../static/icons/urban_roadnet_parking_free_bld_24.svg';
import urban_service_factory_24 from '../../static/icons/urban_service_factory_24.svg';
import urban_service_nursing_room_24 from '../../static/icons/urban_service_nursing_room_24.svg';
import urban_service_ticket_transport_24 from '../../static/icons/urban_service_ticket_transport_24.svg';
import urban_service_toilet_24 from '../../static/icons/urban_service_toilet_24.svg';
import urban_service_toilet_disabled_24 from '../../static/icons/urban_service_toilet_disabled_24.svg';
import urban_sport_skatingrink_24 from '../../static/icons/urban_sport_skatingrink_24.svg';
import vet_clinic_24 from '../../static/icons/vet_clinic_24.svg';
import veterinary_24 from '../../static/icons/veterinary_24.svg';
import viewpoint_24 from '../../static/icons/viewpoint_24.svg';
import waterfall_24 from '../../static/icons/waterfall_24.svg';
import waterpark_24 from '../../static/icons/waterpark_24.svg';
import wc_24 from '../../static/icons/wc_24.svg';
import wedding_24 from '../../static/icons/wedding_24.svg';
import well_24 from '../../static/icons/well_24.svg';
import wine_24 from '../../static/icons/wine_24.svg';
import ya_electro_station_24 from '../../static/icons/ya_electro_station_24.svg';
import yoga_24 from '../../static/icons/yoga_24.svg';
import zoo_24 from '../../static/icons/zoo_24.svg';

import type {Icons} from './types';
export const icons: Icons = {
  administration: administration_24,
  airfield: airfield_24,
  airport: airport_24,
  animation: animation_24,
  aquarium: aquarium_24,
  architect_bureau: architect_bureau_24,
  armenian_church: armenian_church_24,
  art: art_24,
  atm: atm_24,
  attraction: attraction_24,
  auto: auto_24,
  auto_parts: auto_parts_24,
  auto_repair: auto_repair_24,
  baby_shop: baby_shop_24,
  banks: banks_24,
  bars: bars_24,
  baths: baths_24,
  beach: beach_24,
  beauty: beauty_24,
  beauty_shops: beauty_shops_24,
  beer_market: beer_market_24,
  bike: bike_24,
  bike_rent: bike_rent_24,
  boat_station: boat_station_24,
  bookstore: bookstore_24,
  bowling: bowling_24,
  buddhism: buddhism_24,
  building: building_24,
  bus: bus_24,
  bus_station: bus_station_24,
  bus_stop: bus_stop_24,
  butcher_shop: butcher_shop_24,
  cableway: cableway_24,
  cafe: cafe_24,
  canteen: canteen_24,
  car: car_24,
  car_park: car_park_24,
  car_park_barrier: car_park_barrier_24,
  car_park_covered: car_park_covered_24,
  car_park_disabled: car_park_disabled_24,
  car_park_taxi: car_park_taxi_24,
  car_park_toll: car_park_toll_24,
  car_wash: car_wash_24,
  cart_parking: cart_parking_24,
  catholic_church: catholic_church_24,
  cemetery: cemetery_24,
  checkpoint: checkpoint_24,
  childrens_camp: childrens_camp_24,
  childrens_playground: childrens_playground_24,
  cinemas: cinemas_24,
  circus: circus_24,
  clothes_shop: clothes_shop_24,
  college: college_24,
  concert_hall: concert_hall_24,
  confectionary: confectionary_24,
  construction_hypermarket: construction_hypermarket_24,
  construction_tool: construction_tool_24,
  country: country_24,
  currency_exchange: currency_exchange_24,
  currency_exchange_fallback: currency_exchange_fallback_24,
  dairy: dairy_24,
  dancehall: dancehall_24,
  dental: dental_24,
  district: district_24,
  dolmus: dolmus_24,
  driving_school: driving_school_24,
  drop_off: drop_off_24,
  drugstores: drugstores_24,
  dry_cleaning: dry_cleaning_24,
  electronics: electronics_24,
  emergency: emergency_24,
  entertainments: entertainments_24,
  entrance: entrance_24,
  equestrian: equestrian_24,
  exhibition_center: exhibition_center_24,
  factory: factory_24,
  fallback: fallback_24,
  fast_food: fast_food_24,
  fast_tram: fast_tram_24,
  festival: festival_24,
  film_studio: film_studio_24,
  fire_station: fire_station_24,
  fish_store: fish_store_24,
  fitness: fitness_24,
  flower_shop: flower_shop_24,
  food_market: food_market_24,
  forest: forest_24,
  fountain: fountain_24,
  funicular: funicular_24,
  furniture_store: furniture_store_24,
  gallery: gallery_24,
  garage_cooperative: garage_cooperative_24,
  garden: garden_24,
  gasstation: gasstation_24,
  gastro_market: gastro_market_24,
  geyser: geyser_24,
  giftshop: giftshop_24,
  golf: golf_24,
  government: government_24,
  grass: grass_24,
  greengrocery: greengrocery_24,
  hairdressers: hairdressers_24,
  haulier: haulier_24,
  helicopter: helicopter_24,
  home_appliances: home_appliances_24,
  hospital: hospital_24,
  hostels: hostels_24,
  hotels: hotels_24,
  household_supplies: household_supplies_24,
  hydro: hydro_24,
  hypermarket: hypermarket_24,
  indoor_exit: indoor_exit_24,
  indoor_info_arrival: indoor_info_arrival_24,
  indoor_info_departure: indoor_info_departure_24,
  indoor_info_inquiry_office: indoor_info_inquiry_office_24,
  indoor_info_meetingpoint: indoor_info_meetingpoint_24,
  indoor_info_schedule: indoor_info_schedule_24,
  indoor_info_scheme: indoor_info_scheme_24,
  indoor_info_stand: indoor_info_stand_24,
  indoor_infra_control_frame: indoor_infra_control_frame_24,
  indoor_infra_elevator: indoor_infra_elevator_24,
  indoor_infra_elevator_disabled: indoor_infra_elevator_disabled_24,
  indoor_infra_emergency_exit: indoor_infra_emergency_exit_24,
  indoor_infra_escalator: indoor_infra_escalator_24,
  indoor_infra_fire_stairs: indoor_infra_fire_stairs_24,
  indoor_infra_luggage_inspection: indoor_infra_luggage_inspection_24,
  indoor_infra_pandus: indoor_infra_pandus_24,
  indoor_infra_stairs: indoor_infra_stairs_24,
  indoor_infra_travolator: indoor_infra_travolator_24,
  indoor_leisure_scene: indoor_leisure_scene_24,
  indoor_serivce_smoking_room: indoor_serivce_smoking_room_24,
  indoor_service_charging_socket: indoor_service_charging_socket_24,
  indoor_service_checkin_desk: indoor_service_checkin_desk_24,
  indoor_service_fitting_room: indoor_service_fitting_room_24,
  indoor_service_luggage: indoor_service_luggage_24,
  indoor_service_luggage_claim: indoor_service_luggage_claim_24,
  indoor_service_luggage_oversized_claim: indoor_service_luggage_oversized_claim_24,
  indoor_service_luggage_oversized_dropoff: indoor_service_luggage_oversized_dropoff_24,
  indoor_service_luggage_storage: indoor_service_luggage_storage_24,
  indoor_service_shopping_cart_parking: indoor_service_shopping_cart_parking_24,
  indoor_service_shower: indoor_service_shower_24,
  indoor_service_ticket_office: indoor_service_ticket_office_24,
  indoor_service_waiting_room: indoor_service_waiting_room_24,
  indoor_service_wardrobe: indoor_service_wardrobe_24,
  indoor_service_wheelchair_rent: indoor_service_wheelchair_rent_24,
  industrial_enterprise: industrial_enterprise_24,
  information: information_24,
  it: it_24,
  jewelry_store: jewelry_store_24,
  justice: justice_24,
  kindergarten: kindergarten_24,
  landmark: landmark_24,
  laundry: laundry_24,
  library: library_24,
  liquor_store: liquor_store_24,
  locality: locality_24,
  locker: locker_24,
  malls: malls_24,
  market: market_24,
  marketplace: marketplace_24,
  medical: medical_24,
  medicine: medicine_24,
  memorable_event: memorable_event_24,
  metro: metro_24,
  metro_bus: metro_bus_24,
  metro_cable: metro_cable_24,
  metro_funicular: metro_funicular_24,
  metro_light: metro_light_24,
  metro_monorail: metro_monorail_24,
  metro_tram: metro_tram_24,
  mobile_phones: mobile_phones_24,
  monument: monument_24,
  mosque: mosque_24,
  mountain: mountain_24,
  museum: museum_24,
  music_store: music_store_24,
  musicclub: musicclub_24,
  nail_studio: nail_studio_24,
  news: news_24,
  night_club: night_club_24,
  office: office_24,
  office_service: office_service_24,
  online_store: online_store_24,
  opticial_store: opticial_store_24,
  orthodox_church: orthodox_church_24,
  park: park_24,
  pawnshop: pawnshop_24,
  pedestrian: pedestrian_24,
  perfume_shop: perfume_shop_24,
  pet_playground: pet_playground_24,
  petshop: petshop_24,
  photo: photo_24,
  picnic: picnic_24,
  pier: pier_24,
  pizzeria: pizzeria_24,
  planetarium: planetarium_24,
  playground: playground_24,
  police: police_24,
  police_post: police_post_24,
  pool_hall: pool_hall_24,
  port: port_24,
  post_festival: post_festival_24,
  post_office: post_office_24,
  printing_services: printing_services_24,
  protestant_church: protestant_church_24,
  province: province_24,
  pub: pub_24,
  racing: racing_24,
  railway_entrance: railway_entrance_24,
  railway_station: railway_station_24,
  railway_terminal: railway_terminal_24,
  restaurants: restaurants_24,
  rezervation: rezervation_24,
  route: route_24,
  sanatorium: sanatorium_24,
  school: school_24,
  science: science_24,
  shoe_store: shoe_store_24,
  shooting: shooting_24,
  skating_rink: skating_rink_24,
  ski_resort: ski_resort_24,
  software: software_24,
  spa: spa_24,
  sport: sport_24,
  sport_school: sport_school_24,
  sportcenter: sportcenter_24,
  sports_bar: sports_bar_24,
  spring: spring_24,
  stadium: stadium_24,
  stage: stage_24,
  standpipe: standpipe_24,
  stationery_store: stationery_store_24,
  stenograffia: stenograffia_24,
  street: street_24,
  supermarket: supermarket_24,
  sushi: sushi_24,
  swimming_pool: swimming_pool_24,
  synagogue: synagogue_24,
  tableware: tableware_24,
  tailor: tailor_24,
  taxfree: taxfree_24,
  taxi: taxi_24,
  tennis: tennis_24,
  theatre: theatre_24,
  ticket_office: ticket_office_24,
  tire_fitting: tire_fitting_24,
  tram: tram_24,
  tram_stop: tram_stop_24,
  transport_bus: transport_bus_24,
  transport_tram: transport_tram_24,
  trash: trash_24,
  travel_agency: travel_agency_24,
  university: university_24,
  urban_gov_station_administration: urban_gov_station_administration_24,
  urban_gov_station_attendant: urban_gov_station_attendant_24,
  urban_leisure_house_of_culture: urban_leisure_house_of_culture_24,
  urban_med_first_aid_post: urban_med_first_aid_post_24,
  urban_roadnet_parking_free_bld: urban_roadnet_parking_free_bld_24,
  urban_service_factory: urban_service_factory_24,
  urban_service_nursing_room: urban_service_nursing_room_24,
  urban_service_ticket_transport: urban_service_ticket_transport_24,
  urban_service_toilet: urban_service_toilet_24,
  urban_service_toilet_disabled: urban_service_toilet_disabled_24,
  urban_sport_skatingrink: urban_sport_skatingrink_24,
  vet_clinic: vet_clinic_24,
  veterinary: veterinary_24,
  viewpoint: viewpoint_24,
  waterfall: waterfall_24,
  waterpark: waterpark_24,
  wc: wc_24,
  wedding: wedding_24,
  well: well_24,
  wine: wine_24,
  ya_electro_station: ya_electro_station_24,
  yoga: yoga_24,
  zoo: zoo_24
};
